language: csharp
solution: NStack.sln
script:
  - msbuild /t:restore $TRAVIS_BUILD_DIR/NStack.sln
  - cd $TRAVIS_BUILD_DIR
  - msbuild /p:Configuration=Release NStack.sln
  - nunit-console4 ./NStackTests/bin/Release/NStackTests.dll
mono: "5.8.0"
os: "osx"
